### ISSUE TITLE
alpha.18 not working with typescript 4.2.x

### ISSUE THREAD

**Issue by bwgjoseph** [bwgjoseph/mongoose-vs-ottoman#52]
Hi,

update: seem like this is caused by upgrading to `typescript: 4.2.2`. Is that a `typescript` problem, or alpha.18 is incompatible with typescript > 4.2?

After upgrading to alpha.18, I tried to run my test but encounter this error

```js
test/ts/$and.test.ts:37:31 - error TS2511: Cannot create an instance of an abstract class.

37         const eagleAirplane = new Airplane(eagle);
                                 ~~~~~~~~~~~~~~~~~~~

    at createTSError (Z:\mongoose-vs-ottoman\node_modules\ts-node\src\index.ts:513:12)
    at reportTSError (Z:\mongoose-vs-ottoman\node_modules\ts-node\src\index.ts:517:19)
    at getOutput (Z:\mongoose-vs-ottoman\node_modules\ts-node\src\index.ts:752:36)
    at Object.compile (Z:\mongoose-vs-ottoman\node_modules\ts-node\src\index.ts:968:32)
    at Module.m._compile (Z:\mongoose-vs-ottoman\node_modules\ts-node\src\index.ts:1056:42)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (Z:\mongoose-vs-ottoman\node_modules\ts-node\src\index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.exports.requireOrImport (Z:\mongoose-vs-ottoman\node_modules\mocha\lib\esm-utils.js:42:12)
    at Object.exports.loadFilesAsync (Z:\mongoose-vs-ottoman\node_modules\mocha\lib\esm-utils.js:55:34)
    at Mocha.loadFilesAsync (Z:\mongoose-vs-ottoman\node_modules\mocha\lib\mocha.js:431:19)
    at singleRun (Z:\mongoose-vs-ottoman\node_modules\mocha\lib\cli\run-helpers.js:125:15)
    at exports.runMocha (Z:\mongoose-vs-ottoman\node_modules\mocha\lib\cli\run-helpers.js:190:10)
    at Object.exports.handler (Z:\mongoose-vs-ottoman\node_modules\mocha\lib\cli\run.js:362:11)
    at Z:\mongoose-vs-ottoman\node_modules\yargs\build\index.cjs:443:71
npm ERR! Test failed.  See above for more details.
```

This is the test case - https://github.com/bwgjoseph/mongoose-vs-ottoman/blob/6877ee032fd5a523e1b363d99ee8d7ce63a1cdc5/test/ts/%24and.test.ts#L34

Is there any change that I need to know about, or anything I need to change with alpha.18?

**Comment by bwgjoseph** [comment]
Yes, it works with `4.1.x`
